### ISSUE TITLE
It gaves error without any line of code

### ISSUE THREAD

**Issue by aabuauf** [learn-co-curriculum/activerecord-crud#67]
This lab doesn't work, It gave error when i run learn before typing any line of code. I asked a question and tried with Coach but he has same error.
The error is
```
D, [2019-08-17T11:47:25.299971 #11258] DEBUG -- :    (1.3ms)  SELECT sqlite_version(*)

An error occurred while loading spec_helper.
Failure/Error: raise 'Migrations are pending. Run `rake db:migrate SINATRA_ENV=test` to resolve the issue.'

RuntimeError:
  Migrations are pending. Run `rake db:migrate SINATRA_ENV=test` to resolve theissue.
# ./spec/spec_helper.rb:8:in `<top (required)>'


Finished in 0.00171 seconds (files took 1.46 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00171 seconds (files took 1.46 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

When I tried `rake db:migrate SINATRA_ENV=test`
it gave me 
```
rake db:migrate SINATRA_ENV=test
rake aborted!
LoadError: cannot load such file -- sinatra/activerecord/rake/activerecord_6
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/usr/local/rvm/gems/ruby-2.6.1/gems/sinatra-activerecord-2.0.13/lib/sinatra/activerecord/rake.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/home/proactive-karma-6410/activerecord-crud-online-web-ft-071519/Rakefile:4:in`<top (required)>'
/usr/local/rvm/gems/ruby-2.6.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

**Comment by sgharms** [comment]
Let me address this in issue #66 that you opened.
